defaults:
  - _self_
  - task@_global_: quadruped_walk
  - override hydra/launcher: submitit_local

# task settings
frame_stack: 3
action_repeat: 1
discount: 0.99
# train settings
num_seed_frames: 4000
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: true
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 128  # 可以改
# misc
seed: 1
device: cuda
save_video: true
save_train_video: false
use_tb: True
# experiment
experiment: exp
# agent
use_wandb: false
wandb_group: None
name: svea
use_traj: false
img_size: 84  # 可以改
use_depth: true
hint: none

agent:
  _target_: algos.svea.SVEAAgent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  critic_target_tau: 0.01
  encoder_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  use_wandb: ${use_wandb}
  num_expl_steps: 2000
  stddev_schedule: ${stddev_schedule}  # TODO
  stddev_clip: 0.3
  hidden_dim: 1024  # 可以改
  projection_dim: 256
  num_shared_layers: 11
  num_head_layers: 3
  num_filters: 32
  context_third: 1
  context_ego: 1
  encoder_type: 'pixel'
  init_temperature: 0.2
  multiview: false
  actor_lr: 1e-4
  critic_lr: 1e-4
  alpha_lr: 1e-4
  encoder_lr: 1e-4
  aux_coef: 1
  aux_l2_coef: 1
  aux_latency: 150000
  

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${name}/${now:%H%M%S}_${hydra.job.override_dirname}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${name}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${name}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm
